apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ashwanth01/ashapp:ci   # use exact tag
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "supersecretkey"
          readinessProbe:
            httpGet:
              path: /health    # create /health route in Flask
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
