name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image with 'latest' tag
      - name: Build Docker image
        run: |
          docker build -t ashwanth01/ashapp:latest ./backend

      # 4. Push Docker image
      - name: Push Docker image
        run: |
          docker push ashwanth01/ashapp:latest

      # 5. Apply Deployment (force update)
      - name: Apply Kubernetes deployment
        run: |
          kubectl apply -f ./backend/k8s/backend-deployment.yaml

      # 6. Apply Service (if needed)
      - name: Apply Kubernetes service
        run: |
          kubectl apply -f ./backend/k8s/backend-service.yaml

      # 7. Wait for pod to be ready
      - name: Wait for pod ready
        run: |
          kubectl rollout status deployment/backend-deployment --timeout=120s

      # 8. Show pods and services
      - name: Show Kubernetes status
        run: |
          kubectl get pods
          kubectl get svc

      # 9. Print app URL
      - name: Print app URL
        run: |
          NODE_PORT=$(kubectl get svc backend-service -o jsonpath='{.spec.ports[0].nodePort}')
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
          echo "Flask app is running at: http://$NODE_IP:$NODE_PORT"
